In [61]:
import pandas as pd
import re
import string

In [2]:
df = pd.read_csv(r"C:\Users\carso\Downloads\CS50 Project NEW\sp500.csv")
df.head()

  Symbol                 Name       Sector
0    MMM           3M Company  Industrials
1    AOS      A.O. Smith Corp  Industrials
2    ABT  Abbott Laboratories  Health Care
3   ABBV          AbbVie Inc.  Health Care
4   ABMD          ABIOMED Inc  Health Care

In [99]:
text = """Republic Services, Inc. (NYSE:RSG) is one of the 10 Best Stocks to Buy According to Billionaire Richard Chilton.
Republic Services, Inc. (NYSE:RSG) is one of the largest waste collection companies in America. Its shares are down by 11.5% over the past year and are up by 3% year-to-date. Citi discussed the firm on May 12th as it cut the share price target to $247 from $253 and kept a Buy rating on the shares. Similarly, CIBC also reduced the share price target. It lowered it to $249 from $251 and kept an Outperform rating on the stock. The financial firm discussed Republic Services, Inc. (NYSE:RSG)'s first-quarter earnings and remarked that despite macroeconomic struggles, the results were solid. As part of its earnings, the waste collection firm posted $4.11 billion in revenue and $1.70 in earnings per share to beat analyst estimates of $4.10 billion and $1.64.
Republic Services, Inc. (NYSE:RSG)'s shares are trading at a forward P/E ratio of 29.67, which is higher than the S&P's 21. The firm scored a win earlier this month after the Federal Trade Commission allowed it to acquire assets from TD*X Associates. The latter operates facilities to process hazardous waste.
While we acknowledge the potential of RSG as an investment, we believe certain AI stocks offer greater upside potential and carry less downside risk. If you're looking for an extremely undervalued AI stock that also stands to benefit significantly from Trump-era tariffs and the onshoring trend, see our free report on the best short-term AI stock.
READ NEXT: 33 Stocks That Should Double in 3 Years and Cathie Wood 2026 Portfolio: 10 Best Stocks to Buy.
Disclosure: None. Follow Insider Monkey on Google News. """

In [80]:
ticker = df['Symbol']
name = df['Name']
sector = df['Sector']
txt = "this is just a test".split()

for word in text.split():
    print(word)
    if re.search(r"\((.*?)\)", word) is not None:
        nw = word.split(":",)[1].split(")")[0]
        print(nw)

Republic
Services,
Inc.
(NYSE:RSG)
RSG
is
one
of
the
10
Best
Stocks
to
Buy
According
to
Billionaire
Richard
Chilton.
Republic
Services,
Inc.
(NYSE:RSG)
RSG
is
one
of
the
largest
waste
collection
companies
in
America.
Its
shares
are
down
by
11.5%
over
the
past
year
and
are
up
by
3%
year-to-date.
Citi
discussed
the
firm
on
May
12th
as
it
cut
the
share
price
target
to
$247
from
$253
and
kept
a
Buy
rating
on
the
shares.
Similarly,
CIBC
also
reduced
the
share
price
target.
It
lowered
it
to
$249
from
$251
and
kept
an
Outperform
rating
on
the
stock.
The
financial
firm
discussed
Republic
Services,
Inc.
(NYSE:RSG)'s
RSG
first-quarter
earnings
and
remarked
that
despite
macroeconomic
struggles,
the
results
were
solid.
As
part
of
its
earnings,
the
waste
collection
firm
posted
$4.11
billion
in
revenue
and
$1.70
in
earnings
per
share
to
beat
analyst
estimates
of
$4.10
billion
and
$1.64.
Republic
Services,
Inc.
(NYSE:RSG)'s
RSG
shares
are
trading
at
a
forward
P/E
ratio
of
29.67,
which
is
higher
than
the
S&P's
21.
The
firm
scored
a
win
earlier
this
month
after
the
Federal
Trade
Commission
allowed
it
to
acquire
assets
from
TD*X
Associates.
The
latter
operates
facilities
to
process
hazardous
waste.
While
we
acknowledge
the
potential
of
RSG
as
an
investment,
we
believe
certain
AI
stocks
offer
greater
upside
potential
and
carry
less
downside
risk.
If
you're
looking
for
an
extremely
undervalued
AI
stock
that
also
stands
to
benefit
significantly
from
Trump-era
tariffs
and
the
onshoring
trend,
see
our
free
report
on
the
best
short-term
AI
stock.
READ
NEXT:
33
Stocks
That
Should
Double
in
3
Years
and
Cathie
Wood
2026
Portfolio:
10
Best
Stocks
to
Buy.
Disclosure:
None.
Follow
Insider
Monkey
on
Google
News.

In [ ]:
valid = ["inc.", "corp.", "inc", "co"]
words = text.split()
for i, word in enumerate(words):
    print(word)
    if word.lower() in valid: 
        print(word)

        previous_1 = words[i-1]
        previous_2 = words[i]
        print(previous_1, previous_2)

should look for (ATOM)

In [101]:
valid = ["inc.", "corp.", "inc", "co", "group", "corporation", "systems"]  
companies = name #Valid DF companies

all_companies=[]
title2=[]

def clean_text(text):
    return text.translate(str.maketrans("", "", string.punctuation)).lower()

clean_txt = clean_text(text)

for company in companies:
    clean_company = clean_text(company)

    if clean_company in clean_txt:
        #print("FOUND:", company)
        all_companies.append(company)
        title2.append(text)
    else:
        continue

In [108]:

text = """Republic Services, Inc. (NYSE:RSG) is one of the 10 Best Stocks to Buy According to Billionaire Richard Chilton.
Republic Services, Inc. (NYSE:RSG) is one of the largest waste collection companies in America. Its shares are down by 11.5% over the past year and are up by 3% year-to-date. Citi discussed the firm on May 12th as it cut the share price target to $247 from $253 and kept a Buy rating on the shares. Similarly, CIBC also reduced the share price target. It lowered it to $249 from $251 and kept an Outperform rating on the stock. The financial firm discussed Republic Services, Inc. (NYSE:RSG)'s first-quarter earnings and remarked that despite macroeconomic struggles, the results were solid. As part of its earnings, the waste collection firm posted $4.11 billion in revenue and $1.70 in earnings per share to beat analyst estimates of $4.10 billion and $1.64.
Republic Services, Inc. (NYSE:RSG)'s shares are trading at a forward P/E ratio of 29.67, which is higher than the S&P's 21. The firm scored a win earlier this month after the Federal Trade Commission allowed it to acquire assets from TD*X Associates. The latter operates facilities to process hazardous waste.
While we acknowledge the potential of RSG as an investment, we believe certain AI stocks offer greater upside potential and carry less downside risk. If you're looking for an extremely undervalued AI stock that also stands to benefit significantly from Trump-era tariffs and the onshoring trend, see our free report on the best short-term AI stock.
READ NEXT: 33 Stocks That Should Double in 3 (NYSE:GOOG) Years and Cathie Wood (NYSE:GOOG) 2026 Portfolio: (NYSE:NVDA) 10 Best Stocks to Buy.
Disclosure: None. Follow Insider Monkey on Google News. """

all_tickers=[]
all_companies=[]

#region TICKER AND COMPANY SEARCHES
#   --- TICKER ---
for word in text.split():

    m = re.search(r"\(([A-Z]+):([A-Z.]+)\)", word)
    if m is not None:
        exchange = m.group(1)   # "NYSE"
        nw = m.group(2)         # "NVDA"
        #print(nw)
        if all_tickers:
            if nw not in all_tickers[-1]:
                all_tickers.append(nw)
        else:
            all_tickers.append(nw) #append first no matter what
            

#   --- COMPANIES ---
valid = ["inc.", "corp.", "inc", "co", "group", "corporation", "systems"]  
companies = name #Valid DF companies

def clean_text(text):
    return text.translate(str.maketrans("", "", string.punctuation)).lower()

clean_txt = clean_text(text)

for company in companies:
    clean_company = clean_text(company)

    if clean_company in clean_txt:
        #print("FOUND:", company)
        all_companies.append(company)
        title2.append(text)
    else:
        continue

    print(all_companies)
    print("-"*20)
    print(all_tickers)

['Republic Services Inc']
--------------------
['RSG', 'GOOG', 'NVDA']

5
[1, 2, 3, 4]

In [166]:
txt = """Republic Services, Inc. (NYSE:RSG) is one of the 10 Best Stocks to Buy According to Billionaire Richard Chilton."""
companies = name
valid = ["inc.", "corp.", "inc", "co", "group", "corporation", "systems"] 
split = txt.split()
#for word in split:
    #print(word)
valid_company = []
for company in companies:
    
    if str(company).lower().split()[-1] in valid:
        
        company = company.split(" ")
        del company[-1]
        
        
        valid_company.append(company)
    else:
        valid_company.append(str(company).lower().split())

print(valid_company)

lists = pd.DataFrame(valid_company)

lists.head(n=20)

df2 = pd.read_csv(r"C:\Users\carso\Downloads\CS50 Project NEW\sp500.csv")

ticker = df2['Symbol']
name = df2['Name']
sector = df2['Sector']

lists.head(n=100)

[['3m', 'company'], ['a.o.', 'smith', 'corp'], ['abbott', 'laboratories'], ['AbbVie'], ['ABIOMED'], ['accenture', 'plc'], ['activision', 'blizzard'], ['Adobe'], ['advance', 'auto', 'parts'], ['Advanced', 'Micro', 'Devices'], ['aes', 'corp'], ['AFLAC'], ['Agilent', 'Technologies'], ['Air', 'Products', '&', 'Chemicals'], ['Akamai', 'Technologies'], ['Alaska', 'Air', 'Group'], ['albemarle', 'corp'], ['alexandria', 'real', 'estate', 'equities'], ['alexion', 'pharmaceuticals'], ['align', 'technology'], ['allegion'], ['alliant', 'energy', 'corp'], ['allstate', 'corp'], ['alphabet', 'inc.', '(class', 'a)'], ['alphabet', 'inc.', '(class', 'c)'], ['Altria', 'Group'], ['Amazon.com'], ['amcor', 'plc'], ['ameren', 'corp'], ['American', 'Airlines'], ['american', 'electric', 'power'], ['American', 'Express'], ['American', 'International'], ['American', 'Tower'], ['American', 'Water', 'Works', 'Company'], ['ameriprise', 'financial'], ['amerisourcebergen', 'corp'], ['AMETEK'], ['Amgen'], ['amphenol', 'corp'], ['Analog', 'Devices'], ['ansys'], ['anthem'], ['aon', 'plc'], ['Apache'], ['apartment', 'investment', '&', 'management'], ['Apple'], ['Applied', 'Materials'], ['aptiv', 'plc'], ['Archer-Daniels-Midland'], ['arista', 'networks'], ['arthur', 'j.', 'gallagher', '&', 'co.'], ['assurant'], ['AT&T'], ['atmos', 'energy'], ['Autodesk'], ['automatic', 'data', 'processing'], ['AutoZone'], ['avalonbay', 'communities'], ['avery', 'dennison', 'corp'], ['Baker', 'Hughes'], ['ball', 'corp'], ['bank', 'of', 'america', 'corp'], ['Baxter', 'International'], ['becton', 'dickinson'], ['berkshire', 'hathaway'], ['Best', 'Buy', 'Co.'], ['bio-rad', 'laboratories'], ['Biogen'], ['blackrock'], ['boeing', 'company'], ['Booking', 'Holdings'], ['borgwarner'], ['boston', 'properties'], ['boston', 'scientific'], ['bristol-myers', 'squibb'], ['Broadcom'], ['broadridge', 'financial', 'solutions'], ['Brown-Forman'], ['c.', 'h.', 'robinson', 'worldwide'], ['cabot', 'oil', '&', 'gas'], ['Cadence', 'Design'], ['campbell', 'soup'], ['capital', 'one', 'financial'], ['Cardinal', 'Health'], ['Carmax'], ['Carnival'], ['carrier', 'global'], ['Caterpillar'], ['cboe', 'global', 'markets'], ['CBRE'], ['cdw'], ['celanese'], ['Centene'], ['centerpoint', 'energy'], ['CenturyLink'], ['cerner'], ['CF', 'Industries', 'Holdings'], ['Charles', 'Schwab'], ['charter', 'communications'], ['Chevron'], ['chipotle', 'mexican', 'grill'], ['chubb', 'limited'], ['church', '&', 'dwight'], ['CIGNA'], ['cincinnati', 'financial'], ['Cintas'], ['Cisco'], ['Citigroup'], ['Citizens', 'Financial'], ['Citrix'], ['CME', 'Group'], ['cms', 'energy'], ['coca-cola', 'company'], ['cognizant', 'technology', 'solutions'], ['colgate-palmolive'], ['Comcast'], ['Comerica'], ['conagra', 'brands'], ['concho', 'resources'], ['conocophillips'], ['consolidated', 'edison'], ['constellation', 'brands'], ['Copart'], ['Corning'], ['corteva'], ['Costco', 'Wholesale'], ['Coty'], ['Crown', 'Castle', 'International'], ['CSX'], ['Cummins'], ['cvs', 'health'], ['d.', 'r.', 'horton'], ['Danaher'], ['darden', 'restaurants'], ['DaVita'], ['deere', '&', 'co.'], ['Delta', 'Air', 'Lines'], ['dentsply', 'sirona'], ['devon', 'energy'], ['dexcom'], ['diamondback', 'energy'], ['Digital', 'Realty', 'Trust'], ['discover', 'financial', 'services'], ['discovery', 'inc.', '(class', 'a)'], ['discovery', 'inc.', '(class', 'c)'], ['dish', 'network'], ['dollar', 'general'], ['dollar', 'tree'], ['dominion', 'energy'], ["domino's", 'pizza'], ['Dover'], ['Dow'], ['dte', 'energy', 'co.'], ['duke', 'energy'], ['duke', 'realty', 'corp'], ['DuPont', 'de', 'Nemours'], ['dxc', 'technology'], ['e*trade'], ['eastman', 'chemical'], ['Eaton'], ['eBay'], ['Ecolab'], ['edison', "int'l"], ['edwards', 'lifesciences'], ['electronic', 'arts'], ['emerson', 'electric', 'company'], ['Entergy'], ['eog', 'resources'], ['Equifax'], ['equinix'], ['equity', 'residential'], ['Essex', 'Property', 'Trust'], ['estée', 'lauder', 'companies'], ['everest', 're', 'group', 'ltd.'], ['evergy'], ['eversource', 'energy'], ['Exelon'], ['Expedia'], ['expeditors'], ['extra', 'space', 'storage'], ['Exxon', 'Mobil'], ['f5', 'networks'], ['Facebook'], ['Fastenal'], ['federal', 'realty', 'investment', 'trust'], ['FedEx'], ['fidelity', 'national', 'information', 'services'], ['fifth', 'third', 'bancorp'], ['first', 'republic', 'bank'], ['firstenergy', 'corp'], ['Fiserv'], ['FleetCor', 'Technologies'], ['FLIR'], ['Flowserve'], ['FMC'], ['ford', 'motor', 'company'], ['fortinet'], ['fortive', 'corp'], ['fortune', 'brands', 'home', '&', 'security'], ['fox', 'corporation', '(class', 'a)'], ['fox', 'corporation', '(class', 'b)'], ['franklin', 'resources'], ['Freeport-McMoRan'], ['Gap'], ['garmin', 'ltd.'], ['Gartner'], ['general', 'dynamics'], ['general', 'electric'], ['general', 'mills'], ['general', 'motors'], ['genuine', 'parts'], ['gilead', 'sciences'], ['Global', 'Payments'], ['Globe', 'Life'], ['Goldman', 'Sachs'], ['Grainger', '(W.W.)'], ['h&r', 'block'], ['halliburton', 'co.'], ['Hanesbrands'], ['hartford', 'financial', 'svc.gp.'], ['Hasbro'], ['hca', 'healthcare'], ['healthpeak', 'properties'], ['henry', 'schein'], ['Hess'], ['hewlett', 'packard', 'enterprise'], ['Hilton', 'Worldwide', 'Holdings'], ['hollyfrontier', 'corp'], ['hologic'], ['home', 'depot'], ['Honeywell', "Int'l"], ['Hormel', 'Foods'], ['host', 'hotels', '&', 'resorts'], ['howmet', 'aerospace'], ['HP'], ['Humana'], ['huntington', 'bancshares'], ['huntington', 'ingalls', 'industries'], ['IDEX'], ['idexx', 'laboratories'], ['ihs', 'markit', 'ltd.'], ['illinois', 'tool', 'works'], ['Illumina'], ['incyte'], ['ingersoll', 'rand'], ['Intel'], ['intercontinental', 'exchange'], ['international', 'business', 'machines'], ['international', 'flavors', '&', 'fragrances'], ['international', 'paper'], ['Interpublic'], ['Intuit'], ['Intuitive', 'Surgical'], ['invesco', 'ltd.'], ['IPG', 'Photonics'], ['IQVIA', 'Holdings'], ['iron', 'mountain', 'incorporated'], ['j.', 'b.', 'hunt', 'transport', 'services'], ['jack', 'henry', '&', 'associates'], ['Jacobs', 'Engineering'], ['jm', 'smucker'], ['johnson', '&', 'johnson'], ['johnson', 'controls', 'international'], ['jpmorgan', 'chase', '&', 'co.'], ['juniper', 'networks'], ['kansas', 'city', 'southern'], ['kellogg', 'co.'], ['keycorp'], ['keysight', 'technologies'], ['kimberly-clark'], ['kimco', 'realty'], ['kinder', 'morgan'], ['KLA'], ["Kohl's"], ['Kraft', 'Heinz'], ['kroger', 'co.'], ['L', 'Brands'], ['l3harris', 'technologies'], ['laboratory', 'corp.', 'of', 'america', 'holding'], ['lam', 'research'], ['Lamb', 'Weston', 'Holdings'], ['las', 'vegas', 'sands'], ['leggett', '&', 'platt'], ['leidos', 'holdings'], ['Lennar'], ['lilly', '(eli)', '&', 'co.'], ['lincoln', 'national'], ['linde', 'plc'], ['live', 'nation', 'entertainment'], ['LKQ'], ['Lockheed', 'Martin'], ['Loews'], ["lowe's", 'cos.'], ['lyondellbasell'], ['M&T', 'Bank'], ['Marathon', 'Oil'], ['marathon', 'petroleum'], ['marketaxess'], ['marriott', "int'l."], ['marsh', '&', 'mclennan'], ['martin', 'marietta', 'materials'], ['Masco'], ['Mastercard'], ['Maxim', 'Integrated', 'Products'], ['mccormick', '&', 'co.'], ["McDonald's"], ['McKesson'], ['medtronic', 'plc'], ['merck', '&', 'co.'], ['MetLife'], ['mettler', 'toledo'], ['mgm', 'resorts', 'international'], ['microchip', 'technology'], ['micron', 'technology'], ['Microsoft'], ['mid-america', 'apartments'], ['mohawk', 'industries'], ['molson', 'coors', 'beverage', 'company'], ['mondelez', 'international'], ['monster', 'beverage'], ["moody's", 'corp'], ['morgan', 'stanley'], ['Motorola', 'Solutions'], ['MSCI'], ['mylan', 'n.v.'], ['Nasdaq'], ['National', 'Oilwell', 'Varco'], ['netapp'], ['Netflix'], ['newell', 'brands'], ['Newmont'], ['news', 'corp.', 'class', 'a'], ['news', 'corp.', 'class', 'b'], ['nextera', 'energy'], ['nielsen', 'holdings'], ['Nike'], ['NiSource'], ['noble', 'energy'], ['Norfolk', 'Southern'], ['Northern', 'Trust'], ['northrop', 'grumman'], ['nortonlifelock'], ['norwegian', 'cruise', 'line', 'holdings'], ['nrg', 'energy'], ['Nucor'], ['Nvidia'], ['NVR'], ["o'reilly", 'automotive'], ['occidental', 'petroleum'], ['old', 'dominion', 'freight', 'line'], ['Omnicom'], ['oneok'], ['Oracle'], ['otis', 'worldwide'], ['PACCAR'], ['packaging', 'corporation', 'of', 'america'], ['parker-hannifin'], ['Paychex'], ['paycom'], ['paypal'], ['pentair', 'plc'], ["people's", 'united', 'financial'], ['PepsiCo'], ['perkinelmer'], ['perrigo'], ['Pfizer'], ['philip', 'morris', 'international'], ['phillips', '66'], ['pinnacle', 'west', 'capital'], ['pioneer', 'natural', 'resources'], ['pnc', 'financial', 'services'], ['ppg', 'industries'], ['PPL'], ['Principal', 'Financial'], ['procter', '&', 'gamble'], ['Progressive'], ['prologis'], ['prudential', 'financial'], ['public', 'service', 'enterprise', 'group', '(pseg)'], ['public', 'storage'], ['pultegroup'], ['PVH'], ['qorvo'], ['QUALCOMM'], ['Quanta', 'Services'], ['quest', 'diagnostics'], ['Ralph', 'Lauren'], ['Raymond', 'James', 'Financial'], ['raytheon', 'technologies'], ['Realty', 'Income'], ['Regency', 'Centers'], ['regeneron', 'pharmaceuticals'], ['Regions', 'Financial'], ['Republic', 'Services'], ['resmed'], ['robert', 'half', 'international'], ['Rockwell', 'Automation'], ['Rollins'], ['roper', 'technologies'], ['ross', 'stores'], ['Royal', 'Caribbean'], ['S&P', 'Global'], ['salesforce.com'], ['sba', 'communications'], ['schlumberger', 'ltd.'], ['seagate', 'technology'], ['sealed', 'air'], ['sempra', 'energy'], ['servicenow'], ['sherwin-williams'], ['Simon', 'Property', 'Group'], ['skyworks', 'solutions'], ['sl', 'green', 'realty'], ['snap-on'], ['southern', 'company'], ['southwest', 'airlines'], ['stanley', 'black', '&', 'decker'], ['Starbucks'], ['State', 'Street'], ['steris', 'plc'], ['Stryker'], ['svb', 'financial'], ['synchrony', 'financial'], ['Synopsys'], ['Sysco'], ['t-mobile', 'us'], ['T.', 'Rowe', 'Price'], ['take-two', 'interactive'], ['Tapestry'], ['Target'], ['te', 'connectivity', 'ltd.'], ['technipfmc'], ['teledyne', 'technologies'], ['teleflex'], ['texas', 'instruments'], ['Textron'], ['the', 'bank', 'of', 'new', 'york', 'mellon'], ['the', 'clorox', 'company'], ['the', 'cooper', 'companies'], ['the', 'hershey', 'company'], ['the', 'mosaic', 'company'], ['The', 'Travelers', 'Companies'], ['the', 'walt', 'disney', 'company'], ['thermo', 'fisher', 'scientific'], ['tiffany', '&', 'co.'], ['TJX', 'Companies'], ['tractor', 'supply', 'company'], ['trane', 'technologies', 'plc'], ['TransDigm'], ['truist', 'financial'], ['Twitter'], ['tyler', 'technologies'], ['tyson', 'foods'], ['u.s.', 'bancorp'], ['UDR'], ['ulta', 'beauty'], ['under', 'armour', '(class', 'a)'], ['under', 'armour', '(class', 'c)'], ['union', 'pacific', 'corp'], ['united', 'airlines', 'holdings'], ['United', 'Health', 'Group'], ['united', 'parcel', 'service'], ['United', 'Rentals'], ['universal', 'health', 'services'], ['Unum'], ['valero', 'energy'], ['Varian', 'Medical'], ['Ventas'], ['Verisign'], ['verisk', 'analytics'], ['verizon', 'communications'], ['Vertex', 'Pharmaceuticals'], ['VF'], ['viacomcbs'], ['Visa'], ['vornado', 'realty', 'trust'], ['vulcan', 'materials'], ['W.', 'R.', 'Berkley'], ['Wabtec'], ['walgreens', 'boots', 'alliance'], ['walmart'], ['Waste', 'Management'], ['Waters'], ['WEC', 'Energy'], ['wells', 'fargo'], ['Welltower'], ['west', 'pharmaceutical', 'services'], ['western', 'digital'], ['Western', 'Union'], ['westrock'], ['weyerhaeuser'], ['Whirlpool'], ['williams', 'companies'], ['willis', 'towers', 'watson'], ['wynn', 'resorts', 'ltd'], ['Xcel', 'Energy'], ['xerox'], ['xilinx'], ['Xylem'], ['Yum!', 'Brands'], ['zebra', 'technologies'], ['zimmer', 'biomet', 'holdings'], ['zions', 'bancorp'], ['zoetis']]

              0               1         2    3    4    5
0            3m         company       NaN  NaN  NaN  NaN
1          a.o.           smith      corp  NaN  NaN  NaN
2        abbott    laboratories       NaN  NaN  NaN  NaN
3        AbbVie             NaN       NaN  NaN  NaN  NaN
4       ABIOMED             NaN       NaN  NaN  NaN  NaN
..          ...             ...       ...  ...  ...  ...
95  CenturyLink             NaN       NaN  NaN  NaN  NaN
96       cerner             NaN       NaN  NaN  NaN  NaN
97           CF      Industries  Holdings  NaN  NaN  NaN
98      Charles          Schwab       NaN  NaN  NaN  NaN
99      charter  communications       NaN  NaN  NaN  NaN

[100 rows x 6 columns]

In [ ]:
txt = """Republic Services, Inc. (NYSE:RSG) is one of the 10 Best Stocks to Buy According to Billionaire Richard Chilton."""
companies = name


split = txt.split()
for word in split:
    print(word)

#figure this out use pop to keep a moving list of words match them to see if they fit into the list above

Republic
Services,
Inc.
(NYSE:RSG)
is
one
of
the
10
Best
Stocks
to
Buy
According
to
Billionaire
Richard
Chilton.
6

In [ ]:
import rich

from rich import print
from rich.progress import track
import time as t

for i in track(range(100), description="Progress"):
    t.sleep(.2)

In [12]:
text = """Republic Services, Inc. (NYSE:RSG) is one of the 10 Best Stocks to Buy According to Billionaire Richard Chilton.
Republic Services, Inc. (NYSE:RSG) is one of the largest waste collection companies in America. Its shares are down by 11.5% over the past year and are up by 3% year-to-date. Citi discussed the firm on May 12th as it cut the share price target to $247 from $253 and kept a Buy rating on the shares. Similarly, CIBC also reduced the share price target. It lowered it to $249 from $251 and kept an Outperform rating on the stock. The financial firm discussed Republic Services, Inc. (NYSE:RSG)'s first-quarter earnings and remarked that despite macroeconomic struggles, the results were solid. As part of its earnings, the waste collection firm posted $4.11 billion in revenue and $1.70 in earnings per share to beat analyst estimates of $4.10 billion and $1.64.
Republic Services, Inc. (NYSE:RSG)'s shares are trading at a forward P/E ratio of 29.67, which is higher than the S&P's 21. The firm scored a win earlier this month after the Federal Trade Commission allowed it to acquire assets from TD*X Associates. The latter operates facilities to process hazardous waste.
While we acknowledge the potential of RSG as an investment, we believe certain AI stocks offer greater upside potential and carry less downside risk. If you're looking for an extremely undervalued AI stock that also stands to benefit significantly from Trump-era tariffs and the onshoring trend, see our free report on the best short-term AI stock.
READ NEXT: 33 Stocks That Should Double in 3 Years and Cathie Wood 2026 Portfolio: 10 Best Stocks to Buy.
Disclosure: None. Follow Insider Monkey on Google News."""

In [20]:
from transformers import pipeline
MODEL = "ProsusAI/finbert"

def model(text):

    print("Loading FinBERT...")
    result = pipeline(
        "text-classification",
        model=MODEL,
        tokenizer=MODEL,
        top_k=None
    )
    print(result)

In [ ]:

spl = text.split(".")
print(spl)
print(len(spl))

for i in range(len(spl)):
    model(spl[i+1])

[
    'Republic Services, Inc',
    ' (NYSE:RSG) is one of the 10 Best Stocks to Buy According to Billionaire Richard Chilton',
    '\nRepublic Services, Inc',
    ' (NYSE:RSG) is one of the largest waste collection companies in America',
    ' Its shares are down by 11',
    '5% over the past year and are up by 3% year-to-date',
    ' Citi discussed the firm on May 12th as it cut the share price target to $247 from $253 and kept a Buy rating
on the shares',
    ' Similarly, CIBC also reduced the share price target',
    ' It lowered it to $249 from $251 and kept an Outperform rating on the stock',
    ' The financial firm discussed Republic Services, Inc',
    " (NYSE:RSG)'s first-quarter earnings and remarked that despite macroeconomic struggles, the results were
solid",
    ' As part of its earnings, the waste collection firm posted $4',
    '11 billion in revenue and $1',
    '70 in earnings per share to beat analyst estimates of $4',
    '10 billion and $1',
    '64',
    '\nRepublic Services, Inc',
    " (NYSE:RSG)'s shares are trading at a forward P/E ratio of 29",
    "67, which is higher than the S&P's 21",
    ' The firm scored a win earlier this month after the Federal Trade Commission allowed it to acquire assets from
TD*X Associates',
    ' The latter operates facilities to process hazardous waste',
    '\nWhile we acknowledge the potential of RSG as an investment, we believe certain AI stocks offer greater
upside potential and carry less downside risk',
    " If you're looking for an extremely undervalued AI stock that also stands to benefit significantly from
Trump-era tariffs and the onshoring trend, see our free report on the best short-term AI stock",
    '\nREAD NEXT: 33 Stocks That Should Double in 3 Years and Cathie Wood 2026 Portfolio: 10 Best Stocks to Buy',
    '\nDisclosure: None',
    ' Follow Insider Monkey on Google News',
    ''
]

27

Loading FinBERT...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 39889.05it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 40201.00it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 40204.83it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 50289.61it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 67026.17it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 36170.20it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 33290.76it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 33311.80it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 33483.80it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 28713.43it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 28715.39it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 33539.75it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 33296.02it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 40210.58it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 33278.93it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 40195.25it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 33511.75it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 40224.01it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 33481.14it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 40202.91it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 66988.88it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 33260.55it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 33489.12it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 40201.00it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 33503.76it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 40252.82it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

Loading FinBERT...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 33281.56it/s]

TextClassificationPipeline: {'model': 'BertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu',
'input_modalities': 'text'}

: